num1=int(input("Digite um numero"))
num2=int(input("Digite outro numero"))
soma=int(num1+num2)
subt=int(num1-num2)
mult=int(num1*num2)
divi=int(num1/num2)
print(soma)
print(subt)
print(mult)
print(divi)